name: README Links Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'README.md'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
